#!/usr/bin/env python3
import collections
import os

import yaml
from redis import Redis as RedisClient
from adjust import Adjust

DESC = "Redis adjust driver for Opsani Optune"
VERSION = "0.0.3"
HAS_CANCEL = False

config_path = os.environ.get('OPTUNE_CONFIG', './config.yaml')
secret_path = os.environ.get('OPTUNE_SECRET', './secret.yaml')


def dict_merge(d, m):
    for k, v in m.items():
        if k in d and isinstance(d[k], dict) and isinstance(m[k], collections.Mapping):
            dict_merge(d[k], m[k])
        else:
            d[k] = m[k]


class RedisDriver(Adjust):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.config = self.load_config()
        self.check_config()
        self.client = RedisClient(
            host=self.config.get('redis').get('host', '127.0.0.1'),
            port=self.config.get('redis').get('port', 6379),
            db=self.config.get('redis').get('db', 0),
            password=self.config.get('redis').get('password', ''),
        )

    def check_config(self):
        c = self.config
        assert c and c.get('redis', None), 'Configuration was not provided in "{}". ' \
                                           'Please refer to README.md'.format(config_path)
        r = c.get('redis')
        import json
        raise Exception(json.dumps(c, indent=2))
        assert r.get('settings', None), 'Section "settings" was not provided in "{}". ' \
                                        'Please refer to README.md.'.format(config_path)
        assert r['settings'].get('maxmemory', None), 'Section "settings.maxmemory" was not provided ' \
                                                     'in "{}". Please refer to README.md.'.format(config_path)
        assert r['settings']['maxmemory'].get('min', None), 'Setting "settings.maxmemory.min" was not provided ' \
                                                            'in "{}". Please refer to README.md.'.format(config_path)
        assert r['settings']['maxmemory'].get('max', None), 'Setting "settings.maxmemory.max" was not provided ' \
                                                            'in "{}". Please refer to README.md.'.format(config_path)
        assert r['settings']['maxmemory'].get('step', None), 'Setting "settings.maxmemory.step" was not provided ' \
                                                             'in "{}". Please refer to README.md.'.format(config_path)
        assert r['settings'].get('maxmemory-policy', None), 'Section "settings.maxmemory-policy" was not provided ' \
                                                            'in "{}". Please refer to README.md.'.format(config_path)
        assert r['settings']['maxmemory-policy'].get('values', []), 'Setting "settings.maxmemory.values" was ' \
                                                                    'not provided in "{}". ' \
                                                                    'Please refer to README.md.'.format(config_path)

    @staticmethod
    def load_config():
        try:
            config = yaml.load(open(config_path))
            dict_merge(config, yaml.load(open(secret_path)) if os.path.isfile(secret_path) else {})
            return config
        except yaml.YAMLError:
            raise Exception('Could not parse either config or secret file. Please check their contents.')

    def adjust(self, data=None):
        assert data, 'Received no settings to adjust.'
        settings = data['application']['components']['redis']['settings']
        size = len(settings)

        self.progress = 0
        self.progress_message = "adjusting {} settings".format(size)
        self.print_progress()

        for name, setting in settings.items():
            value = setting['value']

            if name == 'maxmemory':
                value = '{}mb'.format(int(value))

            self.client.config_set(name, value)

        self.progress = 100
        self.progress_message = "adjusted {} settings".format(size)
        self.print_progress()

    def query(self):
        return {
            'components': {
                'redis': {
                    'settings': {
                        'maxmemory': {
                            'type': 'range',
                            'value': int(self.client.config_get('maxmemory')['maxmemory']) // 2**20,
                            'min': self.config.get('settings').get('maxmemory').get('min'),
                            'max': self.config.get('settings').get('maxmemory').get('max'),
                            'step': self.config.get('settings').get('maxmemory').get('step'),
                            'unit': 'megabytes',
                        },
                        'maxmemory-policy': {
                            'type': 'enum',
                            'values': self.config.get('settings').get('maxmemory-policy').get('values'),
                            'value': self.client.config_get('maxmemory-policy')['maxmemory-policy'],
                        },
                    },
                },
            },
        }


if __name__ == '__main__':
    driver = RedisDriver(cli_desc=DESC, supports_cancel=HAS_CANCEL, version=VERSION)
    driver.run()
